name: prueba_wl
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  http: ^0.13.1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/default-welcomer.png
    - images/kenny.png